
version: "3.8"
services:
db:
image: postgres:16
container\_name: postgres\_db
environment:
POSTGRES\_USER: bd_sysgespecole_user\_user
POSTGRES\_PASSWORD: wlfMHSJyFKEjP3FjaMmtIvIPWxuHBYNm
POSTGRES\_DB: bd_sysgespecole
ports:
\- "5432:5432"
restart: always

app:
build: .
container\_name: spring\_app
depends\_on:
\- db
environment:
SPRING\_DATASOURCE\_URL: jdbc\:postgresql://postgres\_db:5432/bd_sysgespecole
SPRING\_DATASOURCE\_USERNAME: bd_sysgespecole_user\_user
SPRING\_DATASOURCE\_PASSWORD: wlfMHSJyFKEjP3FjaMmtIvIPWxuHBYNm
ports:
\- "8080:8080"
