
version: "3.8"
services:
db:
image: postgres:15
container\_name: postgres\_db
environment:
POSTGRES\_USER: sysgespecoledbb\_user
POSTGRES\_PASSWORD: 8jwnkidK8moic9uMaMx1BPaW9N20bse6
POSTGRES\_DB: sysgespecoledbb_1iub
ports:
\- "5432:5432"
restart: always

app:
build: .
container\_name: spring\_app
depends\_on:
\- db
environment:
SPRING\_DATASOURCE\_URL: jdbc\:postgresql://postgres\_db:5432/sysgespecoledbb_1iub
SPRING\_DATASOURCE\_USERNAME: sysgespecoledbb\_user
SPRING\_DATASOURCE\_PASSWORD: 8jwnkidK8moic9uMaMx1BPaW9N20bse6
ports:
\- "8080:8080"
