
version: "3.8"
services:
db:
image: postgres:16
container\_name: postgres\_db
environment:
POSTGRES\_USER: bddsysgespecole\_user
POSTGRES\_PASSWORD: L84pxZ3P6P0BCUekj5ffsfoQpZ51SWM5
POSTGRES\_DB: bddsysgespecole
ports:
\- "5432:5432"
restart: always

app:
build: .
container\_name: spring\_app
depends\_on:
\- db
environment:
SPRING\_DATASOURCE\_URL: jdbc\:postgresql://postgres\_db:5432/bddsysgespecole
SPRING\_DATASOURCE\_USERNAME: bddsysgespecole\_user
SPRING\_DATASOURCE\_PASSWORD: L84pxZ3P6P0BCUekj5ffsfoQpZ51SWM5
ports:
\- "8080:8080"
